import { Question } from '../types';

export const questions: Question[] = [
  {
    id: 'Q001',
    scenario: 'You receive an email from your CEO requesting an urgent wire transfer to a new vendor. The email address looks slightly off: ceo@company-support.com instead of ceo@company.com. What is the most appropriate first response?',
    options: {
      A: 'Process the transfer immediately as it is from the CEO',
      B: 'Verify the request through a separate communication channel like a phone call',
      C: 'Reply to the email asking for more details about the vendor',
      D: 'Forward the email to IT for analysis without taking any action',
    },
    correctAnswer: 'B',
    explanation: 'This is a classic Business Email Compromise (BEC) attack. Always verify urgent financial requests through an independent communication channel. The slight domain variation (company-support.com vs company.com) is a telltale sign of phishing.',
    difficulty: 'medium',
    category: 'Social Engineering',
  },
  {
    id: 'Q002',
    scenario: 'During a routine security audit, you discover unauthorized outgoing traffic on port 4444 from several workstations. What type of attack is most likely occurring?',
    options: {
      A: 'SQL Injection attack',
      B: 'Cross-Site Scripting (XSS)',
      C: 'Metasploit reverse HTTP shell callback',
      D: 'DNS tunneling for data exfiltration',
    },
    correctAnswer: 'C',
    explanation: 'Port 4444 is the default callback port for Metasploit reverse shells. This strongly indicates the systems have been compromised with a Meterpreter payload and are attempting to communicate back to the attacker\'s command server.',
    difficulty: 'hard',
    category: 'Network Security',
  },
  {
    id: 'Q003',
    scenario: 'A user reports their computer is running extremely slow and all their files have mysterious .encrypted extensions. The desktop shows a message demanding Bitcoin payment. What is the immediate containment priority?',
    options: {
      A: 'Attempt to decrypt files using known tools',
      B: 'Isolate the affected machine from the network immediately',
      C: 'Check if the user has recent backups available',
      D: 'Analyze the ransomware sample in a sandbox environment',
    },
    correctAnswer: 'B',
    explanation: 'Network isolation is the immediate priority to prevent lateral movement and stop the ransomware from spreading to other systems. Once contained, you can then assess backup availability and analyze the malware.',
    difficulty: 'easy',
    category: 'Endpoint Security',
  },
  {
    id: 'Q004',
    scenario: 'Your SIEM detects a service account attempting to access multiple file servers it has never accessed before, during odd hours (2 AM). The account also has unusual PowerShell execution history. What is the most likely explanation?',
    options: {
      A: 'A scheduled backup job that was misconfigured',
      B: 'Compromised service account being used for lateral movement',
      C: 'A new automated reporting system deployment',
      D: 'Normal administrative tasks by the IT team',
    },
    correctAnswer: 'B',
    explanation: 'This behavior pattern strongly indicates credential compromise. Service accounts don\'t typically change access patterns suddenly, especially during off-hours combined with suspicious PowerShell activity. This is classic lateral movement behavior.',
    difficulty: 'hard',
    category: 'Endpoint Security',
  },
  {
    id: 'Q005',
    scenario: 'An employee receives a text message claiming to be from IT support asking them to verify their credentials via a link. The message arrives at 3 PM on a Wednesday. What is the correct response?',
    options: {
      A: 'Click the link and enter credentials as it appears to be from IT',
      B: 'Ignore the message as IT never requests credentials via text',
      C: 'Call the helpdesk using the official number to verify the request',
      D: 'Reply asking for more details about the verification requirement',
    },
    correctAnswer: 'C',
    explanation: 'While this is likely a vishing (voice phishing) attempt, the safest verification method is calling the official IT helpdesk number directly rather than using any contact information in the suspicious message.',
    difficulty: 'easy',
    category: 'Social Engineering',
  },
  {
    id: 'Q006',
    scenario: 'You discover aUSB drive in the parking lot labeled "Executive Salary Data - Confidential". What should you do with this device?',
    options: {
      A: 'Plug it into a secure analysis machine to see what\'s on it',
      B: 'Bring it directly to the security team without connecting it to any system',
      C: 'Throw it away as it could be a malicious device',
      D: 'Plug it into a disconnected test machine to examine contents',
    },
    correctAnswer: 'B',
    explanation: 'This is a classic "USB drop" attack used to deliver malware or establish backdoors. The device should be turned over to the security team for forensic analysis in a controlled environment. Never connect unknown USB devices to any system.',
    difficulty: 'easy',
    category: 'Social Engineering',
  },
  {
    id: 'Q007',
    scenario: 'A web application firewall blocks repeated login attempts from IP address 192.168.1.100 to multiple user accounts. The logs show the attempts use different usernames but the same password. What type of attack is this?',
    options: {
      A: 'Credential stuffing attack',
      B: 'Password spray attack',
      C: 'Brute force attack',
      D: 'Rainbow table attack',
    },
    correctAnswer: 'B',
    explanation: 'Password spraying uses a single common password against many usernames. The pattern of using one password across many accounts while rotating usernames is the hallmark of a password spray attack.',
    difficulty: 'medium',
    category: 'Network Security',
  },
  {
    id: 'Q008',
    scenario: 'Your vulnerability scanner reports a critical CVE for a server running an outdated version of OpenSSL. The CVE allows remote code execution without authentication. What is the highest priority action?',
    options: {
      A: 'Schedule the patch for the next maintenance window',
      B: 'Immediately isolate the affected server from the network',
      C: 'Implement a WAF rule to block exploitation attempts',
      D: 'Review logs for indicators of compromise',
    },
    correctAnswer: 'B',
    explanation: 'Given the critical severity (remote code execution without authentication), the immediate priority is network isolation to prevent potential exploitation. Once isolated, you can patch and investigate. This is a high-risk vulnerability that demands immediate action.',
    difficulty: 'medium',
    category: 'Endpoint Security',
  },
  {
    id: 'Q009',
    scenario: 'An attacker performs DNS poisoning to redirect traffic from your company\'s website to a malicious server. What DNS record type is most likely targeted?',
    options: {
      A: 'MX records',
      B: 'A records and CNAME records',
      C: 'TXT records',
      D: 'PTR records',
    },
    correctAnswer: 'B',
    explanation: 'DNS poisoning typically targets A records (IPv4 addresses) and CNAME records (aliases) to redirect domain traffic. MX records handle email routing and are less commonly targeted for this type of attack.',
    difficulty: 'hard',
    category: 'Network Security',
  },
  {
    id: 'Q010',
    scenario: 'A user receives a calendar invite from an unknown sender containing a link to join a video call. The meeting looks like it\'s from the CEO\'s office. What is the safest course of action?',
    options: {
      A: 'Accept and join to avoid missing important meetings',
      B: 'Decline and report to security team',
      C: 'Forward to the CEO for confirmation',
      D: 'Check the sender email domain to verify authenticity',
    },
    correctAnswer: 'B',
    explanation: 'Meeting invitations are a growing attack vector for phishing and malware delivery. The safest approach is to decline and report suspicious calendar invites to the security team for verification.',
    difficulty: 'medium',
    category: 'Social Engineering',
  },
  {
    id: 'Q011',
    scenario: 'Your security team identifies a zero-day vulnerability in a commonly used VPN client. The vendor has not yet released a patch. What is the appropriate immediate mitigation?',
    options: {
      A: 'Wait for the official patch before taking action',
      B: 'Implement network segmentation and additional monitoring for the VPN',
      C: 'Switch to an alternative VPN solution immediately',
      D: 'Disable the VPN service until patch is available',
    },
    correctAnswer: 'B',
    explanation: 'Network segmentation and enhanced monitoring provide defense-in-depth while awaiting a patch. This allows continued business operations while monitoring for exploitation attempts.',
    difficulty: 'hard',
    category: 'Endpoint Security',
  },
  {
    id: 'Q012',
    scenario: 'You detect unusual outbound DNS queries to a suspicious domain. The queries occur every few minutes from multiple internal hosts. What might an attacker be doing?',
    options: {
      A: 'Performing a DDoS attack on the domain',
      B: 'Using DNS tunneling to exfiltrate data',
      C: 'Running a legitimate cloud sync service',
      D: 'Attempting to resolve internal hostnames',
    },
    correctAnswer: 'B',
    explanation: 'DNS tunneling is a technique used to bypass network restrictions and exfiltrate data. Regular, periodic DNS queries to unusual domains from multiple hosts is a classic indicator of DNS tunneling activity.',
    difficulty: 'hard',
    category: 'Network Security',
  },
  {
    id: 'Q013',
    scenario: 'An employee reports they cannot access their email and their phone shows "SIM not supported" message. What type of attack has likely occurred?',
    options: {
      A: 'Phishing attack',
      B: 'SIM swapping attack',
      C: 'Man-in-the-middle attack',
      D: 'Credential stuffing attack',
    },
    correctAnswer: 'B',
    explanation: 'SIM swapping involves an attacker convincing a mobile carrier to transfer the victim\'s phone number to a new SIM card, giving the attacker control of SMS-based authentication. The "SIM not supported" message indicates the SIM has been deactivated.',
    difficulty: 'medium',
    category: 'Social Engineering',
  },
  {
    id: 'Q014',
    scenario: 'A developer pushes a commit containing database credentials embedded in the source code. What is the correct remediation procedure?',
    options: {
      A: 'Delete the commit from the repository history',
      B: 'Immediately rotate the exposed credentials and scan for exposure',
      C: 'Mark the credentials as sensitive in the repo configuration',
      D: 'Replace credentials with environment variables in next commit',
    },
    correctAnswer: 'B',
    explanation: 'The immediate priority is rotating the exposed credentials since they are already committed to version control. Even if you remove them from history, the credentials have been exposed and may have been accessed.',
    difficulty: 'medium',
    category: 'Cryptography & Auth',
  },
  {
    id: 'Q015',
    scenario: 'Your security team discovers a threat actor has gained access through an API key that was hardcoded in a public GitHub repository. The key was exposed for 6 days. What should be the first action?',
    options: {
      A: 'Search GitHub for any other exposed credentials',
      B: 'Audit what the key was used to access and review access logs',
      C: 'Remove the key from the repository immediately',
      D: 'Contact GitHub to request key removal',
    },
    correctAnswer: 'B',
    explanation: 'Before rotating the key, audit its usage and review access logs to understand what the attacker may have accessed. This provides crucial context for the incident response and determines the scope of the breach.',
    difficulty: 'hard',
    category: 'Cryptography & Auth',
  },
  {
    id: 'Q016',
    scenario: 'You implement multi-factor authentication (MFA) using SMS codes. A user reports receiving MFA codes they didn\'t request. What is the most likely cause?',
    options: {
      A: 'The user\'s phone has malware intercepting SMS',
      B: 'Someone is attempting to brute force the account',
      C: 'The user has a weak password that is being tested',
      D: 'SMS MFA codes are inherently vulnerable to interception',
    },
    correctAnswer: 'B',
    explanation: 'Receiving unsolicited MFA codes indicates someone is attempting to authenticate to the account. This is often part of credential stuffing attacks where attackers test stolen credentials. The user should be advised to change their password.',
    difficulty: 'medium',
    category: 'Cryptography & Auth',
  },
  {
    id: 'Q017',
    scenario: 'A user\'s workstation shows signs of a keylogger: unusual mouse movement and slow performance. What is the best forensic approach?',
    options: {
      A: 'Format the machine and restore from backup',
      B: 'Capture memory dump and analyze for keylogger artifacts',
      C: 'Run a full antivirus scan to remove the malware',
      D: 'Disconnect from network and replace the keyboard',
    },
    correctAnswer: 'B',
    explanation: 'Memory forensics is the best approach to capture volatile evidence of keyloggers and other malware. This allows you to analyze running processes, loaded modules, and potential artifacts before the system is cleaned.',
    difficulty: 'hard',
    category: 'Endpoint Security',
  },
  {
    id: 'Q018',
    scenario: 'An attacker intercepts network traffic at a coffee shop using a fake WiFi access point. What type of attack is being performed?',
    options: {
      A: 'Wardriving attack',
      B: 'Evil twin attack',
      C: 'Bluejacking attack',
      D: 'Packet crafting attack',
    },
    correctAnswer: 'B',
    explanation: 'An evil twin attack uses a fraudulent WiFi access point that mimics a legitimate one to intercept network traffic. This is commonly performed in public places like coffee shops.',
    difficulty: 'easy',
    category: 'Network Security',
  },
  {
    id: 'Q019',
    scenario: 'A finance employee receives a call from someone claiming to be from the bank\'s fraud department, asking to verify account details to prevent a "suspicious transaction." What is this attack called?',
    options: {
      A: 'Pretexting attack',
      B: 'Vishing attack',
      C: 'Quid pro quo attack',
      D: 'Watering hole attack',
    },
    correctAnswer: 'B',
    explanation: 'Vishing (voice phishing) uses phone calls to extract sensitive information. The attacker creates a sense of urgency about a "suspicious transaction" to manipulate the victim into revealing account details.',
    difficulty: 'easy',
    category: 'Social Engineering',
  },
  {
    id: 'Q020',
    scenario: 'An organization implements single sign-on (SSO) but uses the same password for SSO and local admin accounts. What is the primary security risk?',
    options: {
      A: 'Single point of failure for authentication',
      B: 'If SSO is compromised, all linked accounts are at risk',
      C: 'Users will forget their passwords more often',
      D: 'SSO will create audit logging conflicts',
    },
    correctAnswer: 'B',
    explanation: 'Credential reuse across SSO and local accounts creates a significant risk. If the SSO provider is compromised or credentials are leaked, attackers gain access to all connected systems. This is especially dangerous for admin accounts.',
    difficulty: 'medium',
    category: 'Cryptography & Auth',
  },
];

export function getRandomQuestions(count: number): Question[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getQuestionById(id: string): Question | undefined {
  return questions.find((q) => q.id === id);
}